apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
  labels:
    
    app.kubernetes.io/name: orion
    helm.sh/chart: orion-1.3.1
    app.kubernetes.io/instance: orion
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: orion
      app.kubernetes.io/instance: orion
  template:
    metadata:
      labels:
        
        app.kubernetes.io/name: orion
        helm.sh/chart: orion-1.3.1
        app.kubernetes.io/instance: orion
        app.kubernetes.io/version: "1.0.1"
        app.kubernetes.io/managed-by: Helm
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
    spec: 
      serviceAccountName: default
      containers:
        - name: orion
          imagePullPolicy: IfNotPresent
          image: "quay.io/fiware/orion-ld:1.1.0"
          
          # special handling for the health check of telefonica/orion
          
          ports:
            - name: http
              containerPort: 1026
              protocol: TCP
            - name: metrics
              containerPort: 8000
              protocol: TCP
          
          # special handling for the health check of telefonica/orion
          
          env:
            # general
            - name: ORIONLD_PORT
              value: "1026"
            - name: ORIONLD_SOCKET_SERVICE
              value: "TRUE"
            - name: ORIONLD_SOCKET_SERVICE_PORT
              value: "1027"
            - name: ORIONLD_DISABLE_FILE_LOG
              value: "TRUE"
            - name: ORIONLD_CACHED_CONTEXT_DIRECTORY
              value: /opt/orion/ldcontexts

            # db
            - name: ORIONLD_MONGO_HOST
              value: orion-mongo:27017
            - name: ORIONLD_MONGO_DB
              value: orion
            

            # tenancy
            
            # metrics
            
            
            - name: ORIONLD_DISABLE_METRICS
              value: "TRUE"
            
            
            - name: ORIONLD_STAT_COUNTERS
              value: "FALSE"
            
            
            - name: ORIONLD_STAT_SEM_WAIT
              value: "FALSE"
            
            - name: ORIONLD_STAT_TIMING
              value: "FALSE"
            
            - name: ORIONLD_STAT_NOTIF_QUEUE
              value: "FALSE"

            # logging
            - name: ORIONLD_LOG_LEVEL
              value: WARN

            ##TROE
            
            
            - name: ORIONLD_TROE
              value: "FALSE"
            - name: ORIONLD_TROE_USER
              value: user
            
            
            - name: ORIONLD_TROE_PWD
              value: password
            
            
            - name: ORIONLD_TROE_HOST
              value: postgres
            
            
            - name: ORIONLD_TROE_PORT
              value: "5432"
            
            
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
