apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-mongo
  labels:
    app.kubernetes.io/name: orion-mongo
    helm.sh/chart: orion-1.3.1
    app.kubernetes.io/instance: orion
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: orion-mongo
      app.kubernetes.io/instance: orion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orion-mongo
        helm.sh/chart: orion-1.3.1
        app.kubernetes.io/instance: orion
        app.kubernetes.io/managed-by: Helm
      
    spec:
      containers:
        - name: mongo-db
          imagePullPolicy: IfNotPresent
          image: "quay.io/opencloudio/ibm-mongodb:4.0.24"
          securityContext:
            runAsUser: 999
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            exec:
              command:
                - bash
                - -ec
                - |
                  mongo --eval 'db.runCommand("ping").ok' 127.0.0.1:27017/test && echo 0 || echo 1
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -ec
                - |
                  mongo --eval 'db.runCommand("ping").ok' 127.0.0.1:27017/test && echo 0 || echo 1
            initialDelaySeconds: 5
            periodSeconds: 5