apiVersion: v1
kind: Service
metadata:
  name: orion-mongo
  labels:
    app.kubernetes.io/name: orion-mongo
    helm.sh/chart: orion-1.3.1
    app.kubernetes.io/instance: orion
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app.kubernetes.io/name: orion-mongo
    app.kubernetes.io/instance: orion