apiVersion: v1
kind: Service
metadata:
  name: orion
  labels:
    
    app.kubernetes.io/name: orion
    helm.sh/chart: orion-1.3.1
    app.kubernetes.io/instance: orion
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 1026
      targetPort: 1026
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: orion
    app.kubernetes.io/instance: orion
