apiVersion: v1
kind: Pod
metadata:
  name: digitaltwin-container  # Fixed pod name
spec:
  containers:
  - name: digitaltwin-container
    image: digitaltwin
    imagePullPolicy: Never
    command: ["sleep", "infinity"]  # Keeps the container alive
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP  # Gets the pod's IP and injects it as an env variable
  restartPolicy: Always

