apiVersion: v1
kind: Pod
metadata:
  name: digitaltwin-container  # Fixed pod name
spec:
  containers:
  - name: digitaltwin-container
    image: harbor.containers.wurnet.nl/training/digitaltwin
    command: ["sleep", "infinity"]  # Keeps the container alive
    resources:
      requests:
        cpu: 100m
        memory: 64M
      limits:
        cpu: 200m
        memory: 512M
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP  # Gets the pod's IP and injects it as an env variable
  restartPolicy: Always

