{
      "RDMSOL": 200,
      "SoilProfileDescription": {
            "PFWiltingPoint": 4.2,
            "PFFieldCapacity": 2.0,
            "SurfaceConductivity": 70,
            "GroundWater": false,
            "SoilLayers": [
                  {
                        "Thickness": 5,
                        "CNRatioSOMI": 8.612059158134244,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.043906,
                        "RHOD": 0.99,
                        "Soil_pH": 6.9,
                        "SMfromPF": [
                              -1.0,
                              0.5518,
                              1.0,
                              0.5307,
                              1.3,
                              0.5092,
                              1.7,
                              0.461,
                              2.0,
                              0.4141,
                              2.3,
                              0.3648,
                              2.4,
                              0.3488,
                              2.7,
                              0.3036,
                              3.0,
                              0.2633,
                              3.3,
                              0.2281,
                              3.7,
                              0.1885,
                              4.0,
                              0.1635,
                              4.2,
                              0.1488,
                              6.0,
                              0.0661
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.7687,
                              1.0,
                              0.8956,
                              1.3,
                              0.5687,
                              1.7,
                              0.0013,
                              2.0,
                              -0.5049,
                              2.3,
                              -1.0536,
                              2.4,
                              -1.2422,
                              2.7,
                              -1.8179,
                              3.0,
                              -2.4019,
                              3.3,
                              -2.9896,
                              3.7,
                              -3.7755,
                              4.0,
                              -4.3656,
                              4.2,
                              -4.7591,
                              6.0,
                              -8.302
                        ]
                  },
                  {
                        "Thickness": 10,
                        "CNRatioSOMI": 9.105691056910569,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.019488000000000002,
                        "RHOD": 1.25,
                        "Soil_pH": 7.1,
                        "SMfromPF": [
                              -1.0,
                              0.4758,
                              1.0,
                              0.4494,
                              1.3,
                              0.4239,
                              1.7,
                              0.3717,
                              2.0,
                              0.3255,
                              2.3,
                              0.2803,
                              2.4,
                              0.266,
                              2.7,
                              0.2269,
                              3.0,
                              0.1931,
                              3.3,
                              0.1643,
                              3.7,
                              0.1328,
                              4.0,
                              0.1134,
                              4.2,
                              0.1022,
                              6.0,
                              0.0429
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.6821,
                              1.0,
                              0.7492,
                              1.3,
                              0.3912,
                              1.7,
                              -0.2151,
                              2.0,
                              -0.74,
                              2.3,
                              -1.2976,
                              2.4,
                              -1.4877,
                              2.7,
                              -2.0646,
                              3.0,
                              -2.647,
                              3.3,
                              -3.2319,
                              3.7,
                              -4.0132,
                              4.0,
                              -4.5996,
                              4.2,
                              -4.9906,
                              6.0,
                              -8.5102
                        ]
                  },
                  {
                        "Thickness": 15,
                        "CNRatioSOMI": 10.311688311688313,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.023026000000000005,
                        "RHOD": 1.35,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.4456,
                              1.0,
                              0.4194,
                              1.3,
                              0.3961,
                              1.7,
                              0.3508,
                              2.0,
                              0.3117,
                              2.3,
                              0.2734,
                              2.4,
                              0.2613,
                              2.7,
                              0.2275,
                              3.0,
                              0.1977,
                              3.3,
                              0.1719,
                              3.7,
                              0.1428,
                              4.0,
                              0.1244,
                              4.2,
                              0.1136,
                              6.0,
                              0.0524
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.4481,
                              1.0,
                              0.4305,
                              1.3,
                              0.0664,
                              1.7,
                              -0.5278,
                              2.0,
                              -1.0291,
                              2.3,
                              -1.5557,
                              2.4,
                              -1.7344,
                              2.7,
                              -2.2757,
                              3.0,
                              -2.8214,
                              3.3,
                              -3.3691,
                              3.7,
                              -4.1004,
                              4.0,
                              -4.6493,
                              4.2,
                              -5.0153,
                              6.0,
                              -8.3098
                        ]
                  },
                  {
                        "Thickness": 30,
                        "CNRatioSOMI": 11.297709923664122,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.017168000000000003,
                        "RHOD": 1.49,
                        "Soil_pH": 7.4,
                        "SMfromPF": [
                              -1.0,
                              0.4055,
                              1.0,
                              0.3823,
                              1.3,
                              0.3626,
                              1.7,
                              0.325,
                              2.0,
                              0.2926,
                              2.3,
                              0.2606,
                              2.4,
                              0.2503,
                              2.7,
                              0.2215,
                              3.0,
                              0.1957,
                              3.3,
                              0.1729,
                              3.7,
                              0.1467,
                              4.0,
                              0.1298,
                              4.2,
                              0.1197,
                              6.0,
                              0.0598
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.2511,
                              1.0,
                              0.1931,
                              1.3,
                              -0.1653,
                              1.7,
                              -0.7375,
                              2.0,
                              -1.2136,
                              2.3,
                              -1.7109,
                              2.4,
                              -1.8793,
                              2.7,
                              -2.3891,
                              3.0,
                              -2.9025,
                              3.3,
                              -3.4177,
                              3.7,
                              -4.1056,
                              4.0,
                              -4.6219,
                              4.2,
                              -4.9661,
                              6.0,
                              -8.0648
                        ]
                  },
                  {
                        "Thickness": 40,
                        "CNRatioSOMI": 7.592592592592592,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.011890000000000001,
                        "RHOD": 1.57,
                        "Soil_pH": 7.5,
                        "SMfromPF": [
                              -1.0,
                              0.3824,
                              1.0,
                              0.3625,
                              1.3,
                              0.345,
                              1.7,
                              0.3106,
                              2.0,
                              0.2802,
                              2.3,
                              0.2498,
                              2.4,
                              0.24,
                              2.7,
                              0.2125,
                              3.0,
                              0.1878,
                              3.3,
                              0.166,
                              3.7,
                              0.1409,
                              4.0,
                              0.1247,
                              4.2,
                              0.115,
                              6.0,
                              0.0576
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.171,
                              1.0,
                              0.1463,
                              1.3,
                              -0.2042,
                              1.7,
                              -0.7699,
                              2.0,
                              -1.245,
                              2.3,
                              -1.7436,
                              2.4,
                              -1.9128,
                              2.7,
                              -2.4254,
                              3.0,
                              -2.9422,
                              3.3,
                              -3.4609,
                              3.7,
                              -4.1538,
                              4.0,
                              -4.6738,
                              4.2,
                              -5.0205,
                              6.0,
                              -8.1418
                        ]
                  },
                  {
                        "Thickness": 100,
                        "CNRatioSOMI": 6.891385767790262,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.010672,
                        "RHOD": 1.59,
                        "Soil_pH": 7.5,
                        "SMfromPF": [
                              -1.0,
                              0.3812,
                              1.0,
                              0.363,
                              1.3,
                              0.3478,
                              1.7,
                              0.3181,
                              2.0,
                              0.2917,
                              2.3,
                              0.2649,
                              2.4,
                              0.2562,
                              2.7,
                              0.2313,
                              3.0,
                              0.2085,
                              3.3,
                              0.1878,
                              3.7,
                              0.1635,
                              4.0,
                              0.1475,
                              4.2,
                              0.1377,
                              6.0,
                              0.0757
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.7558,
                              1.0,
                              -0.3293,
                              1.3,
                              -0.6896,
                              1.7,
                              -1.2672,
                              2.0,
                              -1.751,
                              2.3,
                              -2.2586,
                              2.4,
                              -2.4309,
                              2.7,
                              -2.9531,
                              3.0,
                              -3.4798,
                              3.3,
                              -4.0085,
                              3.7,
                              -4.7149,
                              4.0,
                              -5.2451,
                              4.2,
                              -5.5986,
                              6.0,
                              -8.7812
                        ]
                  }
            ],
            "SubSoilType": {
                  "CNRatioSOMI": 6.891385767790262,
                  "CRAIRC": 0.03,
                  "FSOMI": 0.010672,
                  "RHOD": 1.59,
                  "Soil_pH": 7.5,
                  "Thickness": 100,
                  "SMfromPF": [
                        -1.0,
                        0.3812,
                        1.0,
                        0.363,
                        1.3,
                        0.3478,
                        1.7,
                        0.3181,
                        2.0,
                        0.2917,
                        2.3,
                        0.2649,
                        2.4,
                        0.2562,
                        2.7,
                        0.2313,
                        3.0,
                        0.2085,
                        3.3,
                        0.1878,
                        3.7,
                        0.1635,
                        4.0,
                        0.1475,
                        4.2,
                        0.1377,
                        6.0,
                        0.0757
                  ],
                  "CONDfromPF": [
                        -1.0,
                        0.7558,
                        1.0,
                        -0.3293,
                        1.3,
                        -0.6896,
                        1.7,
                        -1.2672,
                        2.0,
                        -1.751,
                        2.3,
                        -2.2586,
                        2.4,
                        -2.4309,
                        2.7,
                        -2.9531,
                        3.0,
                        -3.4798,
                        3.3,
                        -4.0085,
                        3.7,
                        -4.7149,
                        4.0,
                        -5.2451,
                        4.2,
                        -5.5986,
                        6.0,
                        -8.7812
                  ]
            }
      }
}