@startuml
'https://plantuml.com/class-diagram
class AgriParcel {
    + location: GeoProperty
    + area: Float
    + description: String
}
class AgriCrop {
    + description: String
    + plantingFrom: DateTime
}
class AgriSoil {
    + type: String
    + properties: String
}
class AgriParcelOperation {
    + plannedStartAt: DateTime
    + operationType: String
}
class Device {
    + deviceId: String
    + type: String
    + controlledProperty: String
}
class DeviceMeasurement {
    + dateObserved: Date
    + numValue: Float
}
class AgriPest {
    + description: String
}
class AgriProductType {
    + name: String
}

/'
class FeatureCollection {
    + type: String = "FeatureCollection"
    + features: List<Feature>
}
class Feature {
    + type: String = "Feature"
    + geometry: Geometry
    + properties: Map<String, Any>
}
class Geometry {
    + type: String
    + coordinates: List<Float>
}
AgriParcel "1" o-- "1" FeatureCollection : location
FeatureCollection "1" *-- "0..*" Feature : features
Feature "1" *-- "1" Geometry : geometry
'/

AgriParcel  --> AgriCrop : hasAgriCrop
AgriParcel --> AgriSoil : hasAgriSoil
AgriCrop --> AgriSoil : hasAgriSoil
AgriCrop --> AgriPest : hasAgriPest
Device --> DeviceMeasurement: refDevice
Device --> AgriPest: ControlledAsset
AgriParcelOperation --> AgriParcel : hasAgriParcel
AgriParcelOperation --> AgriProductType : hasAgriProductType
Device  --> AgriCrop : ControlledAsset
@enduml
