name: Release
on: [push, pull_request, workflow_dispatch]

permissions:
  pull-requests: write
  contents: write
  issues: write
  packages: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run:
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Smart-Droplets-Project/smartDropletsDataAdapters.git ../
        git clone https://github.com/WUR-AI/A-scab.git ../
