name: Release
on: [push, pull_request, workflow_dispatch]

permissions:
  pull-requests: write
  contents: write
  issues: write
  packages: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Test GITHUB_TOKEN Access
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/Smart-Droplets-Project/repos
    - name: Clone Private Repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://x-access-token:${GITHUB_TOKEN}@github.com/Smart-Droplets-Project/smartDropletsDataAdapters.git ../smartDropletsDataAdapters
        git clone https://github.com/WUR-AI/A-scab.git ../A-scab
