name: Release
on: [push, pull_request, workflow_dispatch]

permissions:
  pull-requests: write
  contents: write
  issues: write
  packages: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Clone Private Repository
      run: |
        git clone git@github.com:Smart-Droplets-Project/smartDropletsDataAdapters.git
        git clone https://github.com/WUR-AI/A-scab.git ../A-scab
