name: Release
on:
  push:
    branches:
      - release

permissions:
  pull-requests: write
  contents: write
  issues: write
  packages: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t digitaltwin -f Dockerfile ../

    - name: Authenticate with GHCR
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag Docker Image
      run: |
        LOWERCASE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        docker tag digitaltwin ghcr.io/${LOWERCASE_REPO}/digitaltwin:${{ github.sha }}
        docker tag digitaltwin ghcr.io/${LOWERCASE_REPO}/digitaltwin:latest

    - name: Push Docker Image to GHCR
      run: |
        LOWERCASE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/${LOWERCASE_REPO}/digitaltwin:${{ github.sha }}
        docker push ghcr.io/${LOWERCASE_REPO}/digitaltwin:latest